# Generated by Django 5.2.4 on 2025-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_customer_id_cart_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product_categories',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='shop.productcategory'),
        ),
    ]
